use serde::Serialize;

#[derive(Debug, Clone, Serialize)]
#[serde(tag = "type")]
pub enum DebugEvent {
    ScanlineAdvance {
        frame: u64,
        cycle: u64,
        from_ly: u8,
        to_ly: u8,
    },
    PpuModeChange {
        frame: u64,
        cycle: u64,
        from_mode: String,
        to_mode: String,
        ly: u8,
    },
    ScanlineRender {
        frame: u64,
        cycle: u64,
        ly: u8,
    },
    OamDmaStart {
        frame: u64,
        cycle: u64,
        source: u16,
    },
    OamDmaComplete {
        frame: u64,
        cycle: u64,
        source: u16,
        bytes: u16,
    },
    GdmaStallEstimate {
        frame: u64,
        cycle: u64,
        blocks: u8,
        stall_cycles: u32,
    },
    HdmaStart {
        frame: u64,
        cycle: u64,
        source: u16,
        dest: u16,
        blocks: u8,
        hblank_mode: bool,
    },
    HdmaBlock {
        frame: u64,
        cycle: u64,
        source: u16,
        dest: u16,
        block_index: u8,
        remaining_blocks: u8,
        hblank_mode: bool,
        stall_cycles: u32,
    },
    HdmaComplete {
        frame: u64,
        cycle: u64,
        source: u16,
        dest: u16,
        blocks: u8,
        hblank_mode: bool,
    },
    HdmaCancel {
        frame: u64,
        cycle: u64,
        source: u16,
        dest: u16,
        remaining_blocks: u8,
    },
    HdmaDeferred {
        frame: u64,
        cycle: u64,
        remaining_blocks: u8,
        ly: u8,
        reason: String,
    },
    HdmaWriteIgnored {
        frame: u64,
        cycle: u64,
        value: u8,
        remaining_blocks: u8,
    },
    MapperControlWrite {
        frame: u64,
        cycle: u64,
        mapper: String,
        addr: u16,
        value: u8,
        rom_bank: u16,
        ram_bank: u16,
    },
    MapperRomBankChange {
        frame: u64,
        cycle: u64,
        mapper: String,
        addr: u16,
        value: u8,
        from: u16,
        to: u16,
    },
    MapperRamBankChange {
        frame: u64,
        cycle: u64,
        mapper: String,
        addr: u16,
        value: u8,
        from: u16,
        to: u16,
    },
    ApuMasterToggle {
        frame: u64,
        cycle: u64,
        enabled: bool,
        nr52: u8,
    },
    ApuChannelTrigger {
        frame: u64,
        cycle: u64,
        channel: u8,
        reg: u16,
        value: u8,
    },
    ApuChannelLengthExpired {
        frame: u64,
        cycle: u64,
        channel: u8,
    },
    ApuEnvelopeStep {
        frame: u64,
        cycle: u64,
        channel: u8,
        volume: u8,
        increasing: bool,
    },
    ApuSweepStep {
        frame: u64,
        cycle: u64,
        old_frequency: u16,
        new_frequency: u16,
        negate: bool,
        shift: u8,
    },
    ApuChannelDisabled {
        frame: u64,
        cycle: u64,
        channel: u8,
        reason: String,
        reg: u16,
    },
    ApuDacStateChange {
        frame: u64,
        cycle: u64,
        channel: u8,
        enabled: bool,
        reg: u16,
        active: bool,
    },
    ApuPopRisk {
        frame: u64,
        cycle: u64,
        source: String,
        reg: u16,
    },
    ApuFrameSequencerStep {
        frame: u64,
        cycle: u64,
        step: u8,
    },
    ApuMixerControl {
        frame: u64,
        cycle: u64,
        nr50: u8,
        nr51: u8,
        nr52: u8,
    },
    ApuMixedOutput {
        frame: u64,
        cycle: u64,
        left: i16,
        right: i16,
        active_mask: u8,
    },
    ApuPcmFramesBuffered {
        frame: u64,
        cycle: u64,
        frames: u16,
        buffered_frames: u32,
    },
    ApuPcmBufferWrapped {
        frame: u64,
        cycle: u64,
        dropped_frames: u16,
        dropped_total: u64,
    },
    ApuWaveRamWrite {
        frame: u64,
        cycle: u64,
        index: u8,
        value: u8,
    },
    ApuWaveRamAccessAliased {
        frame: u64,
        cycle: u64,
        requested_index: u8,
        actual_index: u8,
        is_write: bool,
    },
    ApuCh3TriggerRetainsSample {
        frame: u64,
        cycle: u64,
        buffered_sample: u8,
        next_index: u8,
    },
    ApuNoiseClockFrozen {
        frame: u64,
        cycle: u64,
        shift: u8,
        divisor_code: u8,
    },
    CgbModeSelected {
        frame: u64,
        cycle: u64,
        cgb_enabled: bool,
        cgb_only: bool,
    },
    CgbVramBankSwitch {
        frame: u64,
        cycle: u64,
        bank: u8,
        value: u8,
    },
    CgbWramBankSwitch {
        frame: u64,
        cycle: u64,
        bank: u8,
        value: u8,
    },
    CgbBgPaletteIndexWrite {
        frame: u64,
        cycle: u64,
        index: u8,
        auto_increment: bool,
    },
    CgbBgPaletteDataWrite {
        frame: u64,
        cycle: u64,
        index: u8,
        value: u8,
        blocked: bool,
        auto_increment: bool,
    },
    CgbObjPaletteIndexWrite {
        frame: u64,
        cycle: u64,
        index: u8,
        auto_increment: bool,
    },
    CgbObjPaletteDataWrite {
        frame: u64,
        cycle: u64,
        index: u8,
        value: u8,
        blocked: bool,
        auto_increment: bool,
    },
    CgbKey1Write {
        frame: u64,
        cycle: u64,
        armed: bool,
        double_speed: bool,
        value: u8,
    },
    CgbSpeedSwitch {
        frame: u64,
        cycle: u64,
        double_speed: bool,
        stop_stall_cycles: u32,
    },
    CgbSpeedSwitchFreeze {
        frame: u64,
        cycle: u64,
        cpu_cycles: u32,
        ppu_mode: u8,
    },
    LcdToggle {
        frame: u64,
        cycle: u64,
        enabled: bool,
        lcdc: u8,
    },
    StatWrite {
        frame: u64,
        cycle: u64,
        old_stat: u8,
        new_stat: u8,
    },
    LycWrite {
        frame: u64,
        cycle: u64,
        old_lyc: u8,
        new_lyc: u8,
    },
    StatSignal {
        frame: u64,
        cycle: u64,
        stat: u8,
        ly: u8,
        lyc: u8,
        coincidence: bool,
    },
    VblankEnter {
        frame: u64,
        cycle: u64,
        ly: u8,
    },
    FrameComplete {
        frame: u64,
        cycle: u64,
        frame_hash: u32,
    },
    BankSwitch {
        frame: u64,
        cycle: u64,
        from: u16,
        to: u16,
        from_symbol: Option<String>,
        to_symbol: Option<String>,
    },
    FarCallSuspected {
        frame: u64,
        cycle: u64,
        from_bank: u16,
        to_bank: u16,
        from_symbol: Option<String>,
        to_symbol: Option<String>,
    },
    KitaqgbIntrinsic {
        frame: u64,
        cycle: u64,
        symbol: String,
        intrinsic_kind: String,
        likely_visible_effect: bool,
        flush_like: bool,
    },
    BankReturnMissing {
        frame: u64,
        cycle: u64,
        expected_bank: u16,
        current_bank: u16,
    },
    TimerInterrupt {
        frame: u64,
        cycle: u64,
        tima: u8,
        tma: u8,
    },
    TimerOverflow {
        frame: u64,
        cycle: u64,
        old_tima: u8,
    },
    TimerReload {
        frame: u64,
        cycle: u64,
        reloaded_tima: u8,
        tma: u8,
    },
    TimerControlWrite {
        frame: u64,
        cycle: u64,
        old_tac: u8,
        new_tac: u8,
    },
    DivResetEdge {
        frame: u64,
        cycle: u64,
        old_div: u16,
    },
    SerialTransferStart {
        frame: u64,
        cycle: u64,
        sb: u8,
        sc: u8,
        internal_clock: bool,
    },
    SerialTransferComplete {
        frame: u64,
        cycle: u64,
        sb: u8,
        sc: u8,
        internal_clock: bool,
    },
    JoypadEdge {
        frame: u64,
        cycle: u64,
        old_mask: u8,
        new_mask: u8,
        p1: u8,
    },
    JoypadRead {
        frame: u64,
        cycle: u64,
        p1: u8,
        select: u8,
        mask: u8,
    },
    JoypadSelectionWrite {
        frame: u64,
        cycle: u64,
        old_p1: u8,
        new_p1: u8,
    },
    JoypadInterrupt {
        frame: u64,
        cycle: u64,
        p1: u8,
    },
    InterruptRequested {
        frame: u64,
        cycle: u64,
        source: String,
        iflag: u8,
    },
    InterruptServiced {
        frame: u64,
        cycle: u64,
        source: String,
        vector: u16,
    },
    InterruptPendingBlocked {
        frame: u64,
        cycle: u64,
        pending_mask: u8,
        ime: bool,
        halted: bool,
    },
    ExecutionStop {
        frame: u64,
        cycle: u64,
        kind: String,
        label: String,
        detail: String,
        pc: u16,
        rom_bank: u16,
        symbol: Option<String>,
        source: Option<String>,
    },
    SymbolContextChange {
        frame: u64,
        cycle: u64,
        rom_bank: u16,
        pc: u16,
        symbol: Option<String>,
        source: Option<String>,
    },
    UnsupportedOpcode {
        frame: u64,
        cycle: u64,
        opcode: u8,
        pc: u16,
        rom_bank: u16,
        symbol: Option<String>,
        source: Option<String>,
    },
    ReplayCheckpointSaved {
        frame: u64,
        cycle: u64,
        checkpoint_index: u64,
        generation: u32,
        digest: u64,
        frame_hash: u32,
        rom_bank: u16,
        pc: u16,
    },
    ReplayRewindApplied {
        frame: u64,
        cycle: u64,
        requested_frames: u64,
        from_frame: u64,
        to_frame: u64,
        checkpoint_index: u64,
        generation: u32,
    },
    ReplayDivergenceDetected {
        frame: u64,
        cycle: u64,
        checkpoint_index: u64,
        generation: u32,
        expected_digest: u64,
        actual_digest: u64,
    },
    BankThrashSuspected {
        frame: u64,
        cycle: u64,
        score: u32,
        bank_a: u16,
        bank_b: u16,
    },
}
